version: '3'
services:
    mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        volumes:
          - ./database:/data/db
        environment:
          - MONGODB_CONNECTION_STRING=mongodb://mehrdad:m123456@mongodb
    backend:
        build: ./backend
        image: backend:latest
        environment:
          - MONGO_ROOT_USERNAME=mehrdad
          - MONGO_ROOT_PASSWORD=m12345  
        ports:
          - "3000:3000"
        links:
          - mongodb:27017
        restart: on-failure

    frontend:
        build: ./frontend
        image: frontend:latest
        ports:
          - "8000:8000"
